apiVersion: batch/v1
kind: Job
metadata:
  name: pg-create-databases
  namespace: postgresql
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-databases
          image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
          command: ["sh", "-c"]
          args:
            - |
              psql -h pg-cluster-rw -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'nextcloud'" | grep -q 1 || psql -h pg-cluster-rw -U postgres -c "CREATE DATABASE nextcloud OWNER nextcloud;"
              psql -h pg-cluster-rw -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'currency_exchange_rates'" | grep -q 1 || psql -h pg-cluster-rw -U postgres -c "CREATE DATABASE currency_exchange_rates OWNER currencyexchangeratessync;"
              psql -h pg-cluster-rw -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'openwebui'" | grep -q 1 || psql -h pg-cluster-rw -U postgres -c "CREATE DATABASE openwebui OWNER openwebui;"
              psql -h pg-cluster-rw -U postgres -d openwebui -c "CREATE EXTENSION IF NOT EXISTS vector;"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-superuser
                  key: password
