apiVersion: v1
kind: Secret
metadata:
  name: currencyexchangeratessync-db-credentials
  namespace: postgresql
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "currency-exchange-rates-sync"
    replicator.v1.mittwald.de/replicate-to: "currency-exchange-rates-sync"
type: Opaque
