apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-credentials
  namespace: postgresql
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "nextcloud"
    replicator.v1.mittwald.de/replicate-to: "nextcloud"
type: Opaque
