apiVersion: v1
kind: Secret
metadata:
  name: openwebui-db-credentials
  namespace: postgresql
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "open-webui"
    replicator.v1.mittwald.de/replicate-to: "open-webui"
type: Opaque
