apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: postgresql
spec:
  instances: 2
  enableSuperuserAccess: true
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"
    shared_preload_libraries:
      - "vchord.so"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  bootstrap:
    initdb:
      database: app
      owner: app

  managed:
    roles:
      - name: nextcloud
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: nextcloud-db-credentials
      - name: currencyexchangeratessync
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: currencyexchangeratessync-db-credentials
      - name: openwebui
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: openwebui-db-credentials
      - name: superset
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: superset-db-credentials
      - name: grafana
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: grafana-db-credentials
      - name: immich
        ensure: present
        login: true
        createdb: false
        superuser: false
        passwordSecret:
          name: immich-db-credentials

  storage:
    storageClass: local-path
    size: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-rw-nodeport
  namespace: postgresql
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: pg-cluster
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP
      name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-ro-nodeport
  namespace: postgresql
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: pg-cluster
    role: replica
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30433
      protocol: TCP
      name: postgresql
